'use client';
import React, { useState, useEffect, useCallback } from 'react';
import dynamic from 'next/dynamic';
import LiveGovernanceState from '@/components/LiveGovernanceState';
import ObservabilityTimeline from '@/components/ObservabilityTimeline';
import type { MetricsResponse } from '@/lib/observability_contract';
const LyapunovVisualizer = dynamic(() => import('@/components/LyapunovVisualizer'), { ssr: false, loading: () => <div className="h-72 rounded-xl bg-slate-900/40 animate-pulse" /> });
const G = { gold: '#c9a84c', navy: '#07070d', surface: '#0f1017', border: '#1a2030' };
interface AgentStat { calls: number; avg_duration_ms: number; error_count: number; error_rate: number; last_call: string | null; }
interface MetricsResponse { timestamp: string; window_minutes: number; agents: Record<string, AgentStat>; system: { total_calls: number; total_interventions: number; intervention_rate: number; avg_m_before: number; avg_m_after: number; avg_governor_effort: number; }; health_distribution: { OPTIMAL: number; ALERT: number; STRESSED: number; CRITICAL: number }; health_status: 'OPTIMAL' | 'ALERT' | 'STRESSED' | 'CRITICAL'; }
const HEALTH_COLOR: Record<string, string> = { OPTIMAL: '#00e5a0', ALERT: '#f7931a', STRESSED: '#ff6b35', CRITICAL: '#ff3b30' };
export default function ObservabilityPage() {
  const [metrics, setMetrics] = useState<MetricsResponse | null>(null); const [loading, setLoading] = useState(true);
  const [metricsError, setMetricsError] = useState(false); const [sessionId, setSessionId] = useState('');
  const [replayMode, setReplayMode] = useState<'idle' | 'auto'>('idle');
  const fetchMetrics = useCallback(async () => { setMetricsError(false); try { const res = await fetch('/api/observability/metrics?session_id=' + encodeURIComponent(sessionId.trim()), { cache: 'no-store' }); if (!res.ok) throw new Error('metrics request failed'); setMetrics(await res.json() as MetricsResponse); } catch (err) { console.error('Failed to fetch metrics:', err); setMetricsError(true); } finally { setLoading(false); } }, []);
  useEffect(() => { void fetchMetrics(); const interval = setInterval(() => void fetchMetrics(), 30000); return () => clearInterval(interval); }, [fetchMetrics]);
  const agentList = metrics ? Object.entries(metrics.agents).map(([name, stat]) => ({ name, ...stat })) : []; const health = metrics?.health_status;
  const updatedAt = metrics ? new Date(metrics.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : null;
  return <div className="min-h-screen" style={{ background: G.navy, color: '#c4cfe0' }}>
    <header style={{ background: G.surface, borderBottom: '1px solid ' + G.border }}><div className="mx-auto max-w-7xl px-4 py-5 sm:px-6 sm:py-6"><span style={{ fontFamily: 'monospace', fontSize: 10, letterSpacing: '0.15em', color: G.gold }}>LEX AUREON</span><h1 className="mt-1 text-xl font-bold text-white sm:text-2xl">Deep Observability</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-gray-400">Live pipeline health, constitutional state, and persisted governance turns.</p></div></header>
    <main className="mx-auto max-w-7xl space-y-5 px-4 py-5 sm:space-y-8 sm:px-6 sm:py-8">
      {loading && <div role="status" className="rounded-xl p-5 text-center text-sm" style={{ background: G.surface, border: '1px solid ' + G.border }}>Loading live metrics…</div>}
      {metricsError && <div role="alert" className="flex flex-col gap-3 rounded-xl border border-amber-700/60 bg-amber-950/30 p-4 text-sm text-amber-100 sm:flex-row sm:items-center sm:justify-between"><span>Live metrics are unavailable. Existing panels may be stale.</span><button type="button" onClick={() => void fetchMetrics()} className="min-h-11 rounded-lg border border-amber-500/60 px-4 font-semibold">Retry</button></div>}
      <section className="space-y-4"><div className="rounded-xl p-4 sm:p-6" style={{ background: G.surface, border: '1px solid ' + G.border }}><h2 className="mb-3 text-base font-bold text-white sm:text-lg">Session filter</h2><input type="text" inputMode="text" autoComplete="off" placeholder="Session ID (optional)" value={sessionId} onChange={(e: React.ChangeEvent<HTMLInputElement>) => setSessionId(e.target.value)} className="min-h-12 w-full rounded-lg px-4 py-3 text-base text-white outline-none focus:ring-2 focus:ring-amber-500" style={{ background: 'rgba(255,255,255,0.05)', border: '1px solid ' + G.border }} /><p className="mt-2 text-xs text-gray-400">Filters the live trajectory and persisted replay below.</p></div><LiveGovernanceState /><ObservabilityTimeline sessionId={sessionId} mode={replayMode} onModeChange={setReplayMode} /></section>
      {metrics && <section className="grid grid-cols-2 gap-3 sm:grid-cols-2 lg:grid-cols-4 sm:gap-4">{[{ label: 'Calls', value: metrics.system.total_calls, color: '#4b8fff' }, { label: 'Interventions', value: metrics.system.total_interventions, color: '#ff6b35' }, { label: 'Intervention rate', value: (metrics.system.intervention_rate * 100).toFixed(1) + '%', color: '#f7931a' }, { label: 'Health', value: health, color: HEALTH_COLOR[health ?? ''] ?? G.gold }].map(metric => <div key={metric.label} className="min-w-0 rounded-xl p-3 sm:p-4" style={{ background: G.surface, border: '1px solid ' + G.border }}><div className="mb-1 truncate text-[9px] uppercase tracking-[0.15em] text-[#4a5870]" style={{ fontFamily: 'monospace' }}>{metric.label}</div><div className="truncate text-lg font-extrabold sm:text-[22px]" style={{ color: metric.color, fontFamily: 'monospace' }}>{metric.value}</div></div>)}</section>}
      {metrics && <div className="grid grid-cols-2 gap-3 text-xs text-gray-400 sm:grid-cols-4"><div>Avg M before <strong className="text-gray-200">{metrics.system.avg_m_before.toFixed(3)}</strong></div><div>Avg M after <strong className="text-gray-200">{metrics.system.avg_m_after.toFixed(3)}</strong></div><div>Avg effort <strong className="text-gray-200">{metrics.system.avg_governor_effort.toFixed(3)}</strong></div><div>Updated <strong className="text-gray-200">{updatedAt}</strong></div></div>}
      <section><h2 className="mb-3 text-lg font-bold text-white sm:mb-4">Constitutional State Trajectory</h2><div className="min-w-0 overflow-hidden rounded-xl"><LyapunovVisualizer sessionId={sessionId || undefined} height={320} /></div></section>
      {agentList.length > 0 && <section className="rounded-xl p-4 sm:p-6" style={{ background: G.surface, border: '1px solid ' + G.border }}><h2 className="mb-4 text-lg font-bold text-white">Agent Performance</h2><div className="space-y-2">{agentList.map(agent => <div key={agent.name} className="flex min-w-0 flex-col gap-2 rounded-lg p-3 sm:flex-row sm:items-center sm:justify-between" style={{ background: 'rgba(255,255,255,0.02)' }}><div className="min-w-0"><div className="truncate font-mono font-bold text-white">{agent.name}</div><div className="text-xs text-gray-400">{agent.calls} executions · {(agent.error_rate * 100).toFixed(1)}% errors</div></div><div className="text-left sm:text-right"><div className="font-mono font-bold" style={{ color: G.gold }}>{agent.avg_duration_ms}ms</div><div className="text-xs text-gray-400">avg latency</div></div></div>)}</div></section>}
      <section className="rounded-xl p-4 sm:p-6" style={{ background: G.surface, border: '1px solid ' + G.border }}><h2 className="mb-3 text-lg font-bold text-white sm:mb-4">About Deep Observability</h2><div className="space-y-3 text-sm leading-6 text-gray-300"><p>Lex Aureon’s pipeline is instrumented around constitutional state and governance receipts.</p><ul className="list-disc space-y-2 pl-5"><li>Live C/R/S/M state with explicit no-data handling</li><li>Persisted governance turns scoped by session</li><li>Interventions, governor effort, and health windows</li><li>Agent latency and error-rate summaries</li></ul></div></section>
    </main></div>;
}